spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/citizen?createDatabaseIfNotExist=true
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

server:
  port: 8081